name: fuelmeter_mobile
description: A minimal Flutter client for FuelMeter with Supabase auth and basic dashboard
publish_to: 'none'

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.7
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  geolocator: ^10.1.0
  http: ^1.2.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/illustrations/
    - assets/logos/




